version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: pg-graphql-test
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: mydatabase
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - hasura-database-network

networks:
  hasura-database-network:
    driver: bridge
    external: true


volumes:
  db:
